# Dockerfile.prod
FROM node:20-alpine AS builder

WORKDIR /usr/src

COPY package*.json ./
RUN npm ci

COPY . .
COPY .env.production ./.env

RUN npm run build

FROM node:20-alpine

WORKDIR /usr/src

COPY --from=builder /usr/src/dist ./dist
COPY --from=builder /usr/src/node_modules ./node_modules
COPY --from=builder /usr/src/package*.json ./
COPY --from=builder /usr/src/.env ./

EXPOSE 3000

CMD ["npm", "run", "start:prod"]