version: '3'
services:
  app:
    image: node:lts
    container_name: test_app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    environment:
      NODE_ENV: test
    command: "npm run test"
    networks:
      - app-network

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: testpassword
      MYSQL_DATABASE: testdb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
