version: '3.8'

services:
  nginx:
    container_name: swapi_nginx:%env.BUILD_NUMBER%
    image: nginx:latest
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./docker/nginx/conf/my_domain.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/html:/usr/share/nginx/html
      - /etc/letsencrypt:/etc/letsencrypt
    networks:
      - swapi_network
    depends_on:
      - app
    restart: always

  mysql:
    container_name: swapi_mysql:%env.BUILD_NUMBER%
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=%env.DB_PASS%
      - MYSQL_DATABASE=%env.DB_NAME%_test
      - MYSQL_USER=%env.DB_USER%
      - MYSQL_PASSWORD=%env.DB_PASS%
    ports:
      - "%env.DB_PORT%:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    networks:
      - swapi_network
    restart: always

  app:
    image: app:%env.BUILD_NUMBER%
    container_name: swapi_app
    build:
      context: .
      dockerfile: Dockerfile.prod
      args:
        - NODE_ENV=production
        - ENV_FILE=.env.production
    environment:
      - NODE_ENV=production
      - DB_HOST=%env.DB_HOST%
      - DB_PORT=%env.DB_PORT%
      - APP_PORT=%env.APP_PORT%
      - DB_NAME=%env.DB_NAME%
      - DB_USER=%env.DB_USER%
      - DB_PASS=%env.DB_PASS%
    working_dir: /usr/src
    volumes:
      - ./:/usr/src
    ports:
      - "%env.APP_PORT%:%env.APP_PORT%"
    networks:
      - swapi_network
    depends_on:
      - mysql
    restart: always

networks:
  swapi_network:
    driver: bridge