version: '3.8'
services:
  mysql-test:
    container_name: swapi_mysql_test
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=%env.DB_PASS%
      - MYSQL_DATABASE=%env.DB_NAME%_test
      - MYSQL_USER=%env.DB_USER%
      - MYSQL_PASSWORD=%env.DB_PASS%
    ports:
      - "3308:3306"
    networks:
      - swapi_network_test
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -p${MYSQL_ROOT_PASSWORD} || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - mysql-test-data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    
  app-test:
    image: app:test
    container_name: swapi_app_test
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NODE_ENV=test
    environment:
      - NODE_ENV=test
      - DB_HOST=mysql-test
      - DB_PORT=3306
      - APP_PORT=3001
      - DB_NAME=%env.DB_NAME%_test
      - DB_USER=%env.DB_USER%
      - DB_PASS=%env.DB_PASS%
    ports:
      - "3001:3000"
    networks:
      - swapi_network_test
    depends_on:
      mysql-test:
        condition: service_healthy

volumes:
  mysql-test-data:
    driver: local

networks:
  swapi_network_test:
    driver: bridge