version: '3.8'
services:
  app:
    image: node:20-alpine
    container_name: test_app
    working_dir: /usr/src
    volumes:
      - .:/usr/src
    environment:
      - NODE_ENV=test
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=test
      - DB_PASS=test_password
      - DB_NAME=swapi_test
    command: "npm run test"
    networks:
      - test_network
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: test_mysql
    environment:
      MYSQL_ROOT_PASSWORD: test_password
      MYSQL_DATABASE: swapi_test
      MYSQL_USER: test
      MYSQL_PASSWORD: test_password
    ports:
      - "3307:3306"
    networks:
      - test_network

networks:
  test_network:
    driver: bridge