# Указание базового образа Node.js для этапа сборки
FROM node:20-alpine AS builder

# Установка рабочей директории
WORKDIR /usr/src

# Аргументы, которые будут переданы из docker-compose.yml
ARG NODE_ENV
ARG ENV_FILE

# Копирование и установка зависимостей
COPY package*.json ./
RUN npm install --upgrade

# Копирование всех файлов проекта
COPY . .

# Копирование нужного .env-файла, зависящего от ENV_FILE
COPY ${ENV_FILE} ./.env

# Компиляция TypeScript в JavaScript
RUN npm run build

# Второй этап: создание финального образа
FROM node:20-alpine

# Установка рабочей директории
WORKDIR /usr/src

# Копирование файлов и директорий из предыдущего этапа
COPY --from=builder /usr/src/dist ./dist
COPY --from=builder /usr/src/node_modules ./node_modules
COPY --from=builder /usr/src/package*.json ./
COPY --from=builder /usr/src/.env ./

# Открытие порта для доступа к приложению
EXPOSE 3000

# Запуск приложения в режиме production
CMD ["npm", "run", "start:prod"]