# Node.js image is used
FROM node:20-alpine

# Working directory inside the container
WORKDIR /usr/src

# Arguments that will be passed from docker-compose.test.yml
ARG NODE_ENV
ARG ENV_FILE

# Copying the rest of the application code
COPY . .

# Remove the node_modules directory to ensure a fresh installation of dependencies
RUN rm -rf node_modules

# Install dependencies based on the package.json file
RUN npm install

# Build the application
RUN npm run build

# Run tests using the specified test file (films.controller.spec.ts)
RUN npm run test -- films.controller.spec.ts
#RUN npm run test
